// dsh-learn 的运行时 skill：注册进宿主 skills 注册表，指导模型使用学习工具。
export const LEARN_SKILL = {
  name: 'learn',
  description: '自我学习工作台：把会话中的经验记录、整理成技能、定期审查修正与退役（Hermes curator 模式移植）。',
  whenToUse: '当用户纠正了你的做法、你踩了坑、发现了可复用模式、用户提到"记住/学习/沉淀"，或需要定期整理技能库时使用。',
  content: [
    '## 用途',
    '',
    'learn 是 dsh 的自我学习系统：把经验变成可复用的技能，并定期维护技能库健康（修正过时、合并重叠、退役无用）。',
    '',
    '## 工作流',
    '',
    '1. **记录**：会话中遇到用户纠正、踩坑教训、偏好、可复用模式时，用 `learn_record` 记一条（kind + content 一句话）。',
    '2. **沉淀**：攒了几条后，用 `learn_draft` 生成技能草案（自动按主题归类），检查内容后 `learn_promote` 发布到 ~/.dsh/skills/（所有会话可见）。',
    '3. **维护**：定期（每周或用户要求时）跑 `learn_review`：自动按最后使用时间把久未使用的技能标 stale、超期归档（可恢复），并派子代理审查重叠/过时/无用技能。',
    '4. **总结**：`learn_summarize` 生成学习周报；`learn_list` 随时查看技能库状态。',
    '',
    '## 工具速览',
    '',
    '- `learn_record`：记录经验（lesson/correction/preference/pattern/tooling）',
    '- `learn_draft`：收件箱条目 → 技能草案',
    '- `learn_promote`：草案 → 正式技能库',
    '- `learn_list`：技能清单 + 生命周期状态',
    '- `learn_review`：审查 pass（生命周期过渡 + 子代理内容审查，默认 dry-run）',
    '- `learn_retire` / `learn_restore`：主动退役 / 恢复（归档可恢复，绝不删除）',
    '- `learn_pin`：钉住技能，防止自动退役',
    '- `learn_summarize`：学习总结',
    '',
    '## 生命周期',
    '',
    '`active`（在用）→ 30 天未用标 `stale` → 90 天未用自动归档（`learn_restore` 可恢复）。pinned 与近期用过的技能永不归档。',
    '',
    '## 注意事项',
    '',
    '- 技能描述（description）要包含触发场景，因为会话技能索引按描述匹配。',
    '- 一次会话一个碎技能是失败的技能库；同类经验合并成一个伞形技能。',
    '- 审查默认 dry-run 只出报告；执行类变更需明确使用 dry_run=false。',
  ],
};
