/**
 * dsh-profile core — profile operations shared by the cordis plugin (index.js)
 * and the standalone CLI (bin/dsh-profile). Pure node:fs logic, no cordis.
 */

import { randomUUID } from "node:crypto";
import {
  existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync,
  rmSync, renameSync, chmodSync,
} from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { execFileSync } from "node:child_process";

export function dshHome() {
  return process.env.DSH_HOME ?? join(homedir(), ".dsh");
}
export function profilesDir() { return join(dshHome(), "profiles"); }
export function defaultProfileFile() { return join(dshHome(), "default-profile"); }
export function wrapperPath() { return join(dshHome(), "bin", "dsh"); }

export function slugify(s) {
  return String(s || "").trim().toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);
}

export function ensureDirs() {
  mkdirSync(profilesDir(), { recursive: true });
  mkdirSync(join(dshHome(), "bin"), { recursive: true });
}

export function listProfiles() {
  ensureDirs();
  const out = [];
  for (const entry of readdirSync(profilesDir(), { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = join(profilesDir(), entry.name);
    if (!existsSync(join(dir, "package.json"))) continue;
    let pkg = {};
    try { pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")); } catch { /* ignore */ }
    const bundles = pkg?.dsh?.profile?.bundles || [];
    const deps = Object.keys(pkg?.dependencies || {});
    let description = "";
    try { description = readFileSync(join(dir, "DESCRIPTION.md"), "utf8").trim(); } catch { /* ignore */ }
    out.push({ name: entry.name, bundles, deps, description });
  }
  return out;
}

export function getCurrent() {
  try { return readFileSync(defaultProfileFile(), "utf8").trim() || null; } catch { return null; }
}

export function assertProfile(name) {
  const dir = join(profilesDir(), name);
  if (!existsSync(join(dir, "package.json"))) throw new Error(`profile 不存在: ${name}`);
  return dir;
}

export function describeProfiles(profiles) {
  if (profiles.length === 0) return "还没有 profile。用 profile_create 创建（或 dsh-profile create <name>）。";
  const current = getCurrent();
  const lines = ["profile 列表（" + profiles.length + " 个）："];
  for (const p of profiles) {
    const mark = p.name === current ? " ← 当前默认" : "";
    const bundle = p.bundles.join(" + ") || "（无 bundle）";
    const deps = p.deps.length > 0 ? "；插件: " + p.deps.join(", ") : "";
    lines.push(`- ${p.name}${mark}：${bundle}${deps}`);
    if (p.description) lines.push(`    ${p.description}`);
  }
  lines.push("");
  lines.push(`当前默认 profile：${current || "未设置（每次需 --profile 显式指定）"}`);
  return lines.join("\n");
}

export function scaffold(name, bundles) {
  const dir = join(profilesDir(), name);
  mkdirSync(dir, { recursive: true });
  const pkg = {
    name: `dsh-profile-${name}`,
    private: true,
    dependencies: {},
    dsh: { profile: { bundles } },
  };
  writeFileSync(join(dir, "package.json"), JSON.stringify(pkg, null, 2) + "\n");
  writeFileSync(join(dir, "cordis.patch.yml"), "# Your patch layer for this dsh profile, applied after every bundle layer:\n# a top-level YAML array of loader patch entries (id-targeted config\n# overrides, disables, and insert lists; `!!js` expressions allowed).\n[]\n");
  writeFileSync(join(dir, "pnpm-workspace.yaml"), "nodeLinker: hoisted\n");
  mkdirSync(join(dir, "plugins"), { recursive: true });
  return dir;
}

export function writeWrapper(current) {
  mkdirSync(join(dshHome(), "bin"), { recursive: true });
  const content = `#!/usr/bin/env bash
# dsh wrapper generated by dsh-profile: boots the default profile.
# Override with DSH_PROFILE=<name> or remove this file to go back to bare dsh.
PROFILE="\${DSH_PROFILE:-${current}}"
exec dsh --profile "$PROFILE" "$@"
`;
  writeFileSync(wrapperPath(), content);
  chmodSync(wrapperPath(), 0o755);
}

export function removeWrapper() {
  try { rmSync(wrapperPath(), { force: true }); } catch { /* ignore */ }
}

/* ---- operations (each returns a human-readable string) ---- */

export function opList() {
  return describeProfiles(listProfiles());
}

export function opCreate(name, { bundles, baseOnly, description } = {}) {
  const n = slugify(name);
  if (!n) throw new Error("profile 名无效（小写字母/数字/连字符）");
  if (listProfiles().some((p) => p.name === n)) throw new Error(`profile 已存在: ${n}`);
  const b = baseOnly
    ? ["@deepseek-ai/dsh-base"]
    : (Array.isArray(bundles) && bundles.length > 0 ? bundles.map(String) : ["@deepseek-ai/dsh-base", "@deepseek-ai/dsh-headless"]);
  const dir = scaffold(n, b);
  if (description) writeFileSync(join(dir, "DESCRIPTION.md"), String(description).trim() + "\n");
  return `已创建 profile ${n}：${dir}\n  bundles: ${b.join(", ")}\n\n下一步：\n  dsh plugin --profile ${n} install\n  dsh --profile ${n} --help`;
}

export function opDelete(name, confirm) {
  const n = slugify(name);
  assertProfile(n);
  if (confirm !== true) throw new Error("删除不可恢复：请确认后传 confirm=true 重试");
  if (n === getCurrent()) throw new Error(`不能删除当前默认 profile ${n}（先 profile_use 切换或清除默认）`);
  const dir = join(profilesDir(), n);
  rmSync(dir, { recursive: true, force: true });
  return `已删除 profile ${n}（${dir}）。`;
}

export function opRename(name, newName) {
  const n = slugify(name);
  const nn = slugify(newName);
  assertProfile(n);
  if (!nn || nn === n) throw new Error("new_name 无效");
  if (listProfiles().some((p) => p.name === nn)) throw new Error(`目标 profile 已存在: ${nn}`);
  renameSync(join(profilesDir(), n), join(profilesDir(), nn));
  if (getCurrent() === n) {
    writeFileSync(defaultProfileFile(), nn + "\n");
    writeWrapper(nn);
    return `已重命名 profile ${n} → ${nn}（默认已跟随）`;
  }
  return `已重命名 profile ${n} → ${nn}`;
}

export function opDescribe(name, description) {
  const n = slugify(name);
  const dir = assertProfile(n);
  if (description !== undefined && description !== null) {
    writeFileSync(join(dir, "DESCRIPTION.md"), String(description).trim() + "\n");
    return `已设置 profile ${n} 描述：${String(description).trim()}`;
  }
  let desc = "";
  try { desc = readFileSync(join(dir, "DESCRIPTION.md"), "utf8").trim(); } catch { /* ignore */ }
  return `profile ${n} 描述：${desc || "（未设置）"}`;
}

export function opUse(name) {
  const n = String(name || "").trim();
  if (n === "") {
    try { rmSync(defaultProfileFile(), { force: true }); } catch { /* ignore */ }
    removeWrapper();
    return "已清除默认 profile。之后每次需 `dsh --profile <name>` 显式指定。";
  }
  const nn = slugify(n);
  assertProfile(nn);
  writeFileSync(defaultProfileFile(), nn + "\n");
  writeWrapper(nn);
  return `已将 ${nn} 设为默认 profile（wrapper: ${wrapperPath()}；DSH_PROFILE 可临时覆盖）。`;
}

export function opExport(name, path) {
  const n = slugify(name);
  const dir = assertProfile(n);
  const outDir = join(dshHome(), "exports");
  mkdirSync(outDir, { recursive: true });
  const outPath = String(path || "").trim() || join(outDir, `${n}-${new Date().toISOString().slice(0, 10)}.tar.gz`);
  execFileSync("tar", ["czf", outPath, "-C", profilesDir(), "--exclude=node_modules", "--exclude=pnpm-lock.yaml", n]);
  return `已导出 profile ${n} → ${outPath}`;
}

export function opImport(archive, name) {
  if (!existsSync(archive)) throw new Error(`归档不存在: ${archive}`);
  const tmp = join(dshHome(), "exports", ".import-" + randomUUID().slice(0, 8));
  mkdirSync(tmp, { recursive: true });
  execFileSync("tar", ["xzf", archive, "-C", tmp]);
  const inner = readdirSync(tmp).filter((e) => !e.startsWith("."));
  if (inner.length !== 1) { rmSync(tmp, { recursive: true, force: true }); throw new Error("归档结构异常：应只含一个 profile 目录"); }
  const srcName = inner[0];
  const nn = slugify(name) || srcName;
  if (listProfiles().some((p) => p.name === nn)) { rmSync(tmp, { recursive: true, force: true }); throw new Error(`profile 已存在: ${nn}`); }
  if (!existsSync(join(tmp, srcName, "package.json"))) { rmSync(tmp, { recursive: true, force: true }); throw new Error("归档内没有 package.json"); }
  renameSync(join(tmp, srcName), join(profilesDir(), nn));
  rmSync(tmp, { recursive: true, force: true });
  return `已导入 profile ${nn}（来自 ${archive}）。需执行 \`dsh plugin --profile ${nn} install\` 安装依赖。`;
}

export function opInfo(name) {
  const n = slugify(name);
  const dir = assertProfile(n);
  let pkg = {};
  try { pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")); } catch { /* ignore */ }
  let desc = "";
  try { desc = readFileSync(join(dir, "DESCRIPTION.md"), "utf8").trim(); } catch { /* ignore */ }
  const lines = [];
  lines.push(`profile ${n}：${dir}`);
  lines.push(`bundles: ${(pkg?.dsh?.profile?.bundles || []).join(", ") || "（无）"}`);
  lines.push(`插件依赖: ${Object.keys(pkg?.dependencies || {}).join(", ") || "（无）"}`);
  if (desc) lines.push(`描述: ${desc}`);
  lines.push(`默认: ${getCurrent() === n ? "是" : "否"}`);
  return lines.join("\n");
}
