/**
 * dsh-scaffold — plugin development toolchain for DeepSeek Harness.
 *
 * Ecosystem gap: dsh is in a fast-breaking rc phase (rc.6 already changed the
 * tool-registration API) and NO scaffolding / verification / compatibility
 * tooling exists yet (only a few skill-level repos, ≤21★). This plugin closes
 * that gap with three tools:
 *
 *   scaffold_plugin — generate an rc.6-compliant plugin skeleton
 *                     (package.json + index.js with defineTool-style tools +
 *                      mock-ctx verify script + README)
 *   verify_plugin   — load a plugin's index.js with a mock ctx and prove that
 *                     every tool registration satisfies the rc.6 contract
 *                     (output.{schema,render} present, presentCall shape,
 *                     name/inject exports, timer inject for ctx.interval)
 *   compat_check    — compare a plugin directory against the installed dsh
 *                     version and scan for known rc.6 API pitfalls
 *                     (tools.register without output, presentResult, ...)
 *
 * @module dsh-scaffold
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, resolve, dirname, basename } from "node:path";
import { homedir } from "node:os";
import { pathToFileURL } from "node:url";
import { execFileSync } from "node:child_process";

export const name = "dsh-scaffold";
export const inject = ["tools", "skills"];

const DSH_HOME = process.env.DSH_HOME ?? join(homedir(), ".dsh");

/* ------------------------------------------------------------------ */
/* helpers                                                             */
/* ------------------------------------------------------------------ */

const present = (title, text) => ({ card: "generic", title, content: [{ type: "text", text: String(text) }] });
const cap = (s, n) => { s = String(s ?? ""); return s.length > n ? s.slice(0, n) + "…" : s; };

function slugify(s) {
  return String(s || "").trim().toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);
}

/** Resolve the installed @deepseek-ai/dsh version. */
export function installedDshVersion() {
  // 1) the running CLI entry's package.json (argv[1] is the dsh launcher script)
  try {
    const entry = resolve(process.argv[1] || "");
    let dir = dirname(entry);
    for (let i = 0; i < 8; i++) {
      const pkg = join(dir, "package.json");
      if (existsSync(pkg)) {
        const j = JSON.parse(readFileSync(pkg, "utf8"));
        if (j.name === "@deepseek-ai/dsh" || j.name === "dsh") return j.version;
      }
      const up = dirname(dir);
      if (up === dir) break;
      dir = up;
    }
  } catch { /* fall through */ }
  // 2) `dsh --version` on PATH (nvm bin first)
  try {
    const bin = "/root/.nvm/versions/node/v22.22.2/bin";
    const out = execFileSync(join(bin, "dsh"), ["--version"], { encoding: "utf8", timeout: 5000 }).trim();
    if (out) return out;
  } catch { /* fall through */ }
  return "unknown";
}

/* ------------------------------------------------------------------ */
/* scaffold_plugin                                                     */
/* ------------------------------------------------------------------ */

const INDEX_TEMPLATE = (name, desc) => `/**
 * ${name} — ${desc}
 *
 * Generated by dsh-scaffold (rc.6 API contract).
 *
 * @module ${name}
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

export const name = "${name}";
export const inject = ["tools", "skills"];

const DSH_HOME = process.env.DSH_HOME ?? join(homedir(), ".dsh");

const present = (title, text) => ({ card: "generic", title, content: [{ type: "text", text: String(text) }] });

export function apply(ctx) {
  const tools = ctx.get("tools");
  const disposers = [];

  tools.register({
    name: "${name}_hello",
    description: "示例工具：返回一句问候。替换成你的真实工具。",
    parameters: {
      type: "object",
      properties: {
        who: { type: "string", description: "问候对象（可选）" },
      },
      required: [],
    },
    output: { schema: { type: "string" }, render: (_args, value) => [{ type: "text", text: String(value) }] },
    async execute(args) {
      return "你好，${name}！(from " + String(args.who || "dsh") + ")";
    },
    presentCall: (args) => present("示例工具", args?.who || ""),
  });

  ctx.effect(() => () => {
    for (const d of disposers) { try { d(); } catch { /* ignore */ } }
  });
}
`;

const VERIFY_TEMPLATE = (name) => `/**
 * Mock-ctx registration check for ${name} (generated by dsh-scaffold).
 * Run: node verify.mjs
 * Passes when every registered tool satisfies the rc.6 contract.
 */
import { pathToFileURL } from "node:url";
import { join, resolve } from "node:path";

const moduleUrl = pathToFileURL(resolve(join(process.argv[2] ?? ".", "index.js"))).href;
const mod = await import(moduleUrl);

const registrations = [];
const skills = [];
const disposers = [];

const ctx = {
  get(service) {
    if (service === "tools") {
      return {
        register: (def) => { registrations.push(def); return () => {}; },
        guard: () => () => {},
      };
    }
    if (service === "skills") {
      return { register: (s) => { skills.push(s); return () => {}; } };
    }
    return null;
  },
  interval() { return () => {}; },
  effect(fn) { if (typeof fn === "function") { const r = fn(); if (typeof r === "function") disposers.push(r); } },
  on() { return () => {}; },
  logger: { info() {}, warn() {}, error() {} },
};

const problems = [];
if (typeof mod.name !== "string" || !mod.name) problems.push("missing/empty name export");
if (!Array.isArray(mod.inject) || !mod.inject.includes("tools")) problems.push("inject must include 'tools'");
if (typeof mod.apply !== "function") problems.push("missing apply(ctx) export");
if (problems.length === 0) mod.apply(ctx);

for (const t of registrations) {
  if (!t.name) problems.push("tool missing name");
  if (!t.description) problems.push(\`tool \${t.name}: missing description\`);
  if (!t.parameters || t.parameters.type !== "object") problems.push(\`tool \${t.name}: parameters must be object schema\`);
  if (!t.output || !t.output.schema) problems.push(\`tool \${t.name}: missing output.schema (rc.6 requirement)\`);
  if (typeof t.output?.render !== "function") problems.push(\`tool \${t.name}: output.render must be a function\`);
  if (typeof t.execute !== "function") problems.push(\`tool \${t.name}: missing execute\`);
  if (t.presentCall !== undefined && typeof t.presentCall !== "function") problems.push(\`tool \${t.name}: presentCall must be a function\`);
}

console.log(JSON.stringify({
  plugin: mod.name,
  tools: registrations.length,
  skills: skills.length,
  problems,
  ok: problems.length === 0,
}, null, 2));
process.exit(problems.length === 0 ? 0 : 1);
`;

const README_TEMPLATE = (name, desc) => `# ${name}

${desc}

Generated by dsh-scaffold. 挂载方式（三选一）：
1. 家级 patch：把 \`${name}\` 目录链接到 \`~/.dsh/plugins/\`，并在 \`~/.dsh/cordis.patch.yml\` 的 insert 列表加一行 \`- id: ${name}\\n  name: ${name}\`
2. profile 级：\`npm pkg set dependencies.${name}="file:../../plugins/${name}"\`（profile 目录下）后 \`dsh plugin --profile <name> install\`
3. 独立 npm 包发布（\`dsh plugin --profile <name> add <pkg>\`）

验证：\`node verify.mjs .\`（mock-ctx 注册检查）。
`;

function scaffoldPlugin({ name: rawName, dir, description, withVerify }) {
  const pname = slugify(rawName);
  if (!pname) throw new Error("name 不能为空（小写连字符）");
  const desc = String(description || "").trim() || "dsh plugin";
  const target = dir ? resolve(String(dir), pname) : resolve(process.cwd(), pname);
  if (existsSync(join(target, "index.js"))) throw new Error(`目标目录已有 index.js: ${target}`);
  mkdirSync(target, { recursive: true });
  writeFileSync(join(target, "package.json"), JSON.stringify({
    name: pname, version: "0.1.0", private: true, type: "module", main: "./index.js", description: desc,
  }, null, 2) + "\n");
  writeFileSync(join(target, "index.js"), INDEX_TEMPLATE(pname, desc));
  writeFileSync(join(target, "README.md"), README_TEMPLATE(pname, desc));
  if (withVerify !== false) writeFileSync(join(target, "verify.mjs"), VERIFY_TEMPLATE(pname));
  return target;
}

/* ------------------------------------------------------------------ */
/* verify_plugin                                                       */
/* ------------------------------------------------------------------ */

function makeMockCtx() {
  const registrations = [];
  const skills = [];
  const disposers = [];
  const ctx = {
    get(service) {
      if (service === "tools") {
        return {
          register: (def) => { registrations.push(def); return () => {}; },
          guard: () => () => {},
        };
      }
      if (service === "skills") {
        return { register: (s) => { skills.push(s); return () => {}; } };
      }
      return null;
    },
    interval() { return () => {}; },
    effect(fn) { if (typeof fn === "function") { const r = fn(); if (typeof r === "function") disposers.push(r); } },
    on() { return () => {}; },
    logger: { info() {}, warn() {}, error() {} },
  };
  return { ctx, registrations, skills, disposers };
}

async function verifyPluginDir(dir) {
  const root = resolve(String(dir));
  const indexPath = join(root, "index.js");
  if (!existsSync(indexPath)) throw new Error(`目录没有 index.js: ${root}`);
  const problems = [];
  const { ctx, registrations, skills } = makeMockCtx();
  let mod;
  try {
    mod = await import(pathToFileURL(indexPath).href);
  } catch (err) {
    return { ok: false, problems: [`import 失败: ${err.message}`], tools: 0, skills: 0 };
  }
  if (typeof mod.name !== "string" || !mod.name) problems.push("缺少 name 导出");
  if (!Array.isArray(mod.inject) || !mod.inject.includes("tools")) problems.push("inject 必须包含 'tools'");
  if (typeof mod.apply !== "function") problems.push("缺少 apply(ctx) 导出");
  if (problems.length === 0) {
    try { mod.apply(ctx); } catch (err) { problems.push(`apply(ctx) 抛错: ${err.message}`); }
  }
  for (const t of registrations) {
    const label = t.name || "<unnamed>";
    if (!t.description) problems.push(`工具 ${label}: 缺 description`);
    if (!t.parameters || t.parameters.type !== "object") problems.push(`工具 ${label}: parameters 必须是 object schema`);
    if (!t.output || !t.output.schema) problems.push(`工具 ${label}: 缺 output.schema（rc.6 强制）`);
    if (typeof t.output?.render !== "function") problems.push(`工具 ${label}: output.render 必须是函数`);
    if (typeof t.execute !== "function") problems.push(`工具 ${label}: 缺 execute`);
    if (t.presentCall !== undefined && typeof t.presentCall !== "function") problems.push(`工具 ${label}: presentCall 必须是函数`);
  }
  return {
    ok: problems.length === 0,
    plugin: mod.name ?? "?",
    tools: registrations.length,
    skills: skills.length,
    problems,
  };
}

/* ------------------------------------------------------------------ */
/* compat_check                                                        */
/* ------------------------------------------------------------------ */

/** Strip comments and quoted strings so naive pattern scans don't false-positive on docs. */
function stripStringsAndComments(text) {
  let out = "";
  let i = 0;
  const n = text.length;
  while (i < n) {
    const c = text[i];
    if (c === "/" && text[i + 1] === "/") {
      while (i < n && text[i] !== "\n") i++;
    } else if (c === "/" && text[i + 1] === "*") {
      i += 2;
      while (i < n && !(text[i] === "*" && text[i + 1] === "/")) i++;
      i += 2;
    } else if (c === '"' || c === "'" || c === "`") {
      const q = c;
      i++;
      while (i < n && text[i] !== q) {
        if (text[i] === "\\") i++;
        i++;
      }
      i++;
      out += " ";
    } else {
      out += c;
      i++;
    }
  }
  return out;
}

function scanPitfalls(root) {
  const found = [];
  const walk = (d) => {
    let entries;
    try { entries = readdirSync(d, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      if (e.name === "node_modules" || e.name === ".git") continue;
      const p = join(d, e.name);
      if (e.isDirectory()) { walk(p); continue; }
      if (!/\.(js|mjs|ts)$/.test(e.name)) continue;
      let raw;
      try { raw = readFileSync(p, "utf8"); } catch { continue; }
      const text = stripStringsAndComments(raw);
      if (/presentResult/.test(text)) found.push({ file: p, issue: "使用已失效的 presentResult（rc.6 改为 output.render）" });
      // ctx.interval without timer in inject
      if (/ctx\.interval/.test(text) && !/inject\s*=\s*\[[^\]]*timer/.test(text)) {
        found.push({ file: p, issue: "ctx.interval 但 inject 未包含 \"timer\"（interval 将永不触发）" });
      }
      // tools.register without output block (rough heuristic)
      if (/tools\.register\s*\(/.test(text) && !/output\s*:/.test(text)) {
        found.push({ file: p, issue: "tools.register 未声明 output（rc.6 强制 {schema, render}）" });
      }
    }
  };
  walk(root);
  return found;
}

function compatCheck(dir) {
  const root = resolve(String(dir || "."));
  const dshVer = installedDshVersion();
  const lines = [`dsh 安装版本: ${dshVer}`, `检查目录: ${root}`];
  const issues = [];
  // package.json sanity
  const pkgPath = join(root, "package.json");
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
      if (pkg.type !== "module") issues.push("package.json 缺 \"type\": \"module\"（插件须为 ESM）");
      if (!pkg.main || !existsSync(join(root, pkg.main))) issues.push(`package.json main 指向不存在的文件: ${pkg.main}`);
    } catch { issues.push("package.json 解析失败"); }
  } else {
    issues.push("目录没有 package.json");
  }
  if (!existsSync(join(root, "index.js"))) issues.push("目录没有 index.js");
  const pitfalls = scanPitfalls(root);
  for (const p of pitfalls) issues.push(`${p.file.replace(root, ".")}: ${p.issue}`);
  lines.push(`发现问题: ${issues.length}`);
  for (const i of issues) lines.push(`- ${i}`);
  const v = dshVer.match(/rc\.(\d+)/);
  lines.push(`提示: 官方声明 rc 阶段会有 breaking changes，插件应跟随安装版本实测（建议跑 verify_plugin）`);
  return { dshVersion: dshVer, issues, ok: issues.length === 0, text: lines.join("\n") };
}

/* ------------------------------------------------------------------ */
/* plugin                                                              */
/* ------------------------------------------------------------------ */

export function apply(ctx) {
  const tools = ctx.get("tools");
  const disposers = [];

  tools.register({
    name: "scaffold_plugin",
    description: "生成一个 rc.6 规范的 dsh 插件骨架：package.json + index.js（含示例工具，output:{schema,render} 契约）+ verify.mjs（mock-ctx 注册检查脚本）+ README.md。用于快速开始插件开发。",
    parameters: {
      type: "object",
      properties: {
        name: { type: "string", description: "插件名（小写连字符，必填）" },
        dir: { type: "string", description: "可选：生成目录（默认当前工作目录，生成 <name>/ 子目录）" },
        description: { type: "string", description: "可选：一句话描述（写入 package.json/README）" },
        with_verify: { type: "boolean", description: "是否生成 verify.mjs（默认 true）" },
      },
      required: ["name"],
    },
    output: { schema: { type: "string" }, render: (_args, value) => [{ type: "text", text: String(value) }] },
    async execute(args) {
      const target = scaffoldPlugin({ name: args.name, dir: args.dir, description: args.description, withVerify: args.with_verify });
      const files = readdirSync(target).sort();
      return `已生成插件骨架 ${basename(target)} → ${target}\n文件: ${files.join(", ")}\n\n下一步：\n1. 编辑 index.js 添加你的工具（保持 output:{schema,render} 契约）\n2. node verify.mjs ${target} 做注册检查\n3. 挂载：链接到 ~/.dsh/plugins/ + 家级 cordis.patch.yml insert 一行（或 profile 依赖）\n4. 用 compat_check 检查 rc.6 兼容性`;
    },
    presentCall: (args) => present("脚手架：生成插件", args?.name || ""),
  });

  tools.register({
    name: "verify_plugin",
    description: "验证一个 dsh 插件目录的 rc.6 注册契约：mock ctx 加载 index.js，逐工具检查 name/description/parameters/output.{schema,render}/execute/presentCall，以及 name/inject 导出。返回检查报告。",
    parameters: {
      type: "object",
      properties: { dir: { type: "string", description: "插件目录（含 index.js 与 package.json）" } },
      required: ["dir"],
    },
    output: { schema: { type: "string" }, render: (_args, value) => [{ type: "text", text: String(value) }] },
    async execute(args) {
      const r = await verifyPluginDir(args.dir);
      const lines = [];
      lines.push(`插件 ${r.plugin}：注册 ${r.tools} 个工具 / ${r.skills} 个技能`);
      if (r.ok) {
        lines.push("✅ 全部通过 rc.6 注册契约检查");
      } else {
        lines.push(`❌ ${r.problems.length} 个问题:`);
        for (const p of r.problems) lines.push(`- ${p}`);
      }
      return lines.join("\n");
    },
    presentCall: (args) => present("脚手架：验证插件", args?.dir || ""),
  });

  tools.register({
    name: "compat_check",
    description: "检查 dsh 插件目录与当前安装 dsh 版本的兼容性：package.json 规范性（ESM/main）、index.js 存在性、rc.6 已知坑扫描（presentResult 失效 API、ctx.interval 缺 timer inject、tools.register 缺 output）。",
    parameters: {
      type: "object",
      properties: { dir: { type: "string", description: "插件目录（默认当前工作目录）" } },
      required: [],
    },
    output: { schema: { type: "string" }, render: (_args, value) => [{ type: "text", text: String(value) }] },
    async execute(args) {
      const r = compatCheck(args.dir || ".");
      return r.text;
    },
    presentCall: () => present("脚手架：兼容性检查", "compat_check"),
  });

  const skillsSvc = ctx.get("skills");
  if (skillsSvc && typeof skillsSvc.register === "function") {
    disposers.push(skillsSvc.register({
      name: "scaffold",
      description: "dsh 插件开发工具链：scaffold_plugin 生成 rc.6 骨架、verify_plugin mock-ctx 注册验证、compat_check 兼容性扫描。",
      whenToUse: "当要开发新 dsh 插件、验证插件能否加载、或排查插件 API 兼容性问题时使用。",
      source: "custom",
      content: [
        "## 用途",
        "",
        "dsh 插件开发三件套：",
        "- `scaffold_plugin name=xxx`：生成 rc.6 规范骨架（index.js + package.json + verify.mjs + README）",
        "- `verify_plugin dir=<目录>`：mock-ctx 加载并逐工具检查注册契约（output:{schema,render} 等）",
        "- `compat_check dir=<目录>`：扫描 rc.6 已知坑（presentResult、timer inject、缺 output）",
        "",
        "## rc.6 关键契约（写插件必守）",
        "",
        "- `tools.register()` 必须带 `output: {schema, render}`（旧 presentResult 已失效）",
        "- `ctx.interval()` 的 inject 必须含 `\"timer\"`，否则定时器永不触发",
        "- 子代理 `run.result.output` 是 blocks 数组不是字符串（取 text 块拼接）",
        "- 本机无 bubblewrap：新 profile 必须在 cordis.patch.yml 覆盖 sandbox-policy(danger-full-access) + approval(never)",
        "- `presentCall` 返回 `{card:'generic', title, content:[{type:'text',text}]}`",
        "",
        "## 挂载插件",
        "",
        "1. 链接到 `~/.dsh/plugins/<name>`（或 profile plugins/ 目录）",
        "2. 家级：`~/.dsh/cordis.patch.yml` insert 列表加 `- id: <name> / name: <name>`",
        "3. profile 级：package.json dependencies 加 `file:` 依赖 + pnpm install",
        "",
        "## 注意",
        "",
        "- 生成骨架后用 `node verify.mjs <目录>` 即可独立验证（不依赖 dsh 运行）",
        "- 官方 API 仍在 breaking change 期：插件应记录目标 rc 版本",
      ],
    }));
  }

  ctx.effect(() => () => {
    for (const d of disposers) { try { d(); } catch { /* ignore */ } }
  });
}
